### ISSUE TITLE
Stay consistant in superfish syntax

### ISSUE THREAD

**Issue by shawntabrizi** [stiiifff/substrate-poe-tutorial#3]
https://github.com/stiiifff/substrate-poe-tutorial/blob/4231f30c1d385b77453324876adc43b72615e0ec/runtime/src/poe.rs#L84

AFAIK `<Thing<T>>::function() == Thing::<T>::function()`

Probably for a first time tutorial, best to maintain a single choice of syntax.

**Comment by stiiifff** [comment]
Just to be sure, which one would go for ? `<Thing<T>>::function()` or `Thing::<T>::function()` ?
I find the [turbofish](https://turbo.fish) syntax easier on the eyes for beginners.
(Assuming that by `superfish` you meant `turbofish`, though we could imagine a `::/T\::` syntax being a fish with a cape 😄

**Comment by shawntabrizi** [comment]
Yes, turbo fish. I think it doesn't matter because long term we should teach them that it is the same, but for this tutorial, makes sense to only use one.

Whatever you like :)
